name: Java CI with Gradle

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - run: 'echo ${{github.event_name}}'
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: List files in the repository
        run: ls
      - name: Build with Gradle
        run: |
          ./backend/gradlew build -p backend

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ vars.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
            docker build -t "${{ vars.DOCKER_USERNAME }}"/"${{ github.repository }}" ./backend
            docker push "${{ vars.DOCKER_USERNAME }}"/"${{ github.repository }}":latest